### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by adem4ik**

### CODE REVIEW

**Comment by q4osteam** [comment]
We can't merge this pull request as original strings "msgid" has been changed. You only need to change the translation strings "msgstr". Please review. Anyway thanks for your effort.

**Comment by adem4ik** [comment]
Well, that change was made by Poedit. Anyway I will fix it.

**Comment by adem4ik** [comment]
- Reverted original "msgid" strings
- A bit more translation updates

**Comment by q4osteam** [comment]
Looks fine, thanks

**Pull request merged**
